### ISSUE TITLE
Bridge Playing UI

### ISSUE THREAD

**Issue by Daithi1** [online-bridge-hackathon/play-engine#14]
This issue deals only with the UI itself. It should hopefully have very little logic in them. E.g. assume these components might have an onClick and some trigger to perform an action. They should not know for example who's turn it is to bid. That will be cover in #17 . 

Things that are needed (feel free to add more):

- [ ] Bidding Box
- [ ] Board number
- [ ] Vulnerability
- [ ] Dealer
- [ ] Cards
- [ ] Own Hand - Front
- [ ] Opps hand - Back
- [ ] Dummy Hand - Back, then Front
- [ ] Tricks taken
- [ ] Contract & declarer
- [ ] Showing board score (e.g. 4S is 420)
- [ ] Showing comparison score (Scored 5 imps on the board) 
- [ ] Showing overall score (Score is 10-5 in imps)
- [ ] Table (the background)

**Comment by Daithi1** [comment]
There are some existing components in https://github.com/online-bridge-hackathon/play-engine/tree/master/userApp/imports/ui/components

**Comment by pociej** [comment]
Closing as too general, @Daithi1 please divide into smaller pieces
